### ISSUE TITLE
Very nice chat-service

### ISSUE THREAD

**Issue by rsdrsd** [an-sh/chat-service#2]
It would be great if you'd also support SockJS. Is that a lot of work and is it even possible, because it doesn't support rooms out of the box?

I also have the following.

Suppose every user has its own room which is named as its username. This user is the admin and owner of this room. From the docs I read that the creator of a room is also the admin/owner. But I don't want this. I want that every user can join/create a room, but it isn't automatically the admin/owner. Only the user whit the same username of the room is the owner/admin. So any user can create a room with a certain username, but it isn't automatically the owner/admin. Only the user with the same username as the roomk can be the owner/admin.

**Comment by an-sh** [comment]
SockJS is just an alternative websocket implementation (like a polyfill). It is not a complete publish/subscribe system, so not build-in backend is available. Also, afaik, it has no rpc-like request/reply implementation (just like a raw websocket). SockJS support will result in implementing many thing that this software is not intended to do.

You can use roomCreateAfter hook, and change an owner with [changeRoomOwner](https://an-sh.github.io/chat-service/0.11/chat-service.ServiceAPI.html#changeRoomOwner) method (available on a service instance). Also you can also use server-side only [roomCreate](https://an-sh.github.io/chat-service/0.11/chat-service.ServiceAPI.html#addRoom) method.
