### ISSUE TITLE
Nest.js support

### ISSUE THREAD

**Issue by iamshouvikmitra** [an-sh/chat-service#21]
How do we implement this library in NestJS. Should it be a gateway or custom provider?

**Comment by an-sh** [comment]
It is not related to NestJS, you can pass raw http/socket.io server
instances if you need to share with some other frameworks. 
https://an-sh.github.io/chat-service/1.0/chat-service.config.html#.SocketIOTransportOptions

**Comment by iamshouvikmitra** [comment]
Thanks for pointing that out.
