### ISSUE TITLE
Get socket id(s) from username

### ISSUE THREAD

**Issue by iamshouvikmitra** [an-sh/chat-service#22]
Firstly, thanks for making this library @an-sh  !
I want to get a list of connected socket id corresponding to a particular username(used during connection from the client)?

Additional Details:
I am trying to add a person to an already created room from the server-side, but I am unable to do that without the socket id. Is there a different approach to this?

**Comment by an-sh** [comment]
You can send a custom system message to a client, then join from a
client.
