### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by bilby91** [an-sh/chat-service#3]
Hello, 

We are building a chatroom ecosystem of applications and we are looking for a simple solution for handling all the messaging infrastructure. We have been evaluating multiple third party solutions but non of them match with our requirements and pricing budget. 

`chat-service` seems to be a really good candidate for our use case, is anyone using this in production ? Do you have a roadmap for the product ?

Thanks before hand!

**Comment by an-sh** [comment]
Hi.

The main thing, it is just an **open source** project, not an out of the box enterprise grade solution with a support. For now i'm focused on other non-related projects, so i don't think i should decide whether it is production ready for your case (budget) or not. As semver suggests anything less that 1.0 should be used with care.

As for feature requests, bug fixes, it will be based only on the feedback for some time.

**Comment by bilby91** [comment]
@an-sh Thanks for the quick reply!

I understand this is an open source project and is not meant to be a plug-n-play enterprise solution. I just wanted to know if you or anybody else was using this in a production environment. 

Thanks and keep up the good work, `chat-service` look really good :)
