### ISSUE TITLE
How to use CommandHooks or how to handle rpc calls

### ISSUE THREAD

**Issue by telion2** [an-sh/chat-service#9]
Hi, 
I'm continuing to use CS. 
I want to add chatroom whenever the user wants to, thus running this on the client: 
` this.socket.emit('roomCreate', roomName, false);` 
However I now want to handle the doubled roomnames. 
I found that there are CommandHooks like roomCreateBefore/After, but I'm a bit confused on how I can use them. 
What I tried was this: 
```
instance.chatService = new ChatService(cs_config,
            {
                onConnect: utils.onConnect,
                roomCreateBefore: utils.roomCreateBefore
            });
//in module utils
roomCreateBefore(server, otherarg) { 
        console.log('got to roomCreate: ' + otherarg);  //-> got to roomCreate: undefined
        //Stuff like if server.hasroom do this else that. 
        return Promise.resolve();
 }
```
Now onConnect works fine because it is part of the HooksInterface where the parameters are exposed. 
But I dont know how I get the 'roomName' parameter of the event roomCreate. 

roomCreateBefore(execInfo, cbopt) → {Promise.<(Array|undefined)>}

I know about the execInfo from the docs aswell but I dont know where to get that and how to use it. 
So to sum my question up: 
How do I handle rpc events from the Client, and if the solution involves CommandHooks, how do I use them properly.

**Comment by an-sh** [comment]
Hi,

You can see an example here: 
https://github.com/an-sh/chat-service/blob/master/test/hooks.js#L62

**Comment by telion2** [comment]
Thanks, I got it to work.
